### ISSUE TITLE
Copy to clipboard icon z-index

### ISSUE THREAD

**Issue by tsm91** [angular/angular.io#837] opened 2016-02-12 19:30 UTC
The z-index of the icon is bigger then the header's. When you scroll down and the code example's icon reaches the header you can see the problem.

Example site: https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

**Comment by wardbell** [comment] 2016-02-15 17:05
Duplicate of #768

**Closed by wardbell** 2016-02-15 17:05 UTC
Labels: duplicate
