### ISSUE TITLE
broken links in glossary

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1123] opened 2016-04-20 01:56 UTC
the link checker reports a bunch of broken links in the glossary. Looks like we incorrectly output the path as `guide/guide`.

@wardbell could you fix? 

```
https://angular.io/docs/ts/latest/guide/glossary.html
  [160, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#interpolation
  [161, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#property-binding
  [162, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#event-binding
  [163, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#attribute-binding
  [164, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#class-binding
  [165, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#style-binding
  [166, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#ng-model
  [169, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#data-binding
  [229, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/dependency-injection.html
  [289, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#property-binding
  [292, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#inputs-outputs
  [301, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#interpolation
  [324, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/lifecycle-hooks.html
  [351, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#property-binding
  [354, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#inputs-outputs
  [367, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/pipes.html
  [381, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/router.html
  [400, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html
  [404, HTTP_404] https://angular.io/docs/ts/latest/guide/guide/template-syntax.html#template-expressions
```

**Comment by naomiblack** [comment] 2016-04-20 03:41
ahh. I see the problem. These broken links are in https://angular.io/docs/ts/latest/guide/glossary.html, which is created by including
```
!= partial("../glossary")
```
in the file `latest/guide/glossary.jade`

But the glossary otherwise lives in `latest/glossary.html` and its links are relative, so this broken link issue is only a problem for the version under guide/

Is that even linked anywhere...?

**Comment by wardbell** [comment] 2016-04-22 17:38
Right. I was stuck.  The partial file exists only because someone might have an old link to it. The proper solution is a redirect to the current location.  I don't know how to do redirects so this was a hack that obviously isn't up to the task.  

If someone can teach me how we do redirects, we can fix this one and a few other cases where I used this inferior technique.

**Comment by chalin** [comment] 2016-05-24 17:22
On a related note, would it not be preferable to have a single "top-level" glossary, rather than the current situation in which the glossary happens to be a chapter in the basic dev. guide? If I understand the current issue reported here, migrating the glossary to the top-level may help address this problem.

**Comment by Foxandxss** [comment] 2016-06-17 14:39
So we still get reports of this problem.

We have a glossary from google with a lot of broken regions and the good one. We should think about removing one and redirect to the good one or similar.

**Comment by wardbell** [comment] 2016-07-06 07:19
This should be fixed in the real server (but not locally!) by the firebase redirect  in PR #1836

**Comment by chalin** [comment] 2016-07-06 13:20
The redirects seem like the right way to go. 

@wardbell : Have you tested #1836 with an actual deploy? Under firebase v2 it might accept the "type", but using v3 is gives an error:
```
Error: hosting.rewrites[4] additionalProperty "type" exists in instance when not allowed
```
Removing both `"type": 301` entries allows the deploy to proceed.

Hopefully Naomi can deploy and we can confirm that the 301 redirects work.

@naomiblack : when will angular.io be migrating to firebase v3 (if at all)? It nicely supports host aliases which makes it much easier for non-googlers to deploy to firebase (without editing the `firebase.json` file every time).

---

Btw, while there are currently no visibly broken links in the guide, the Dart side glossary entries redirect to the TS-side glossary (which is wrong) - #1838. So, if once the 301 redirect has been confirmed to work then we'll be able to fix that.

**Comment by chalin** [comment] 2016-07-06 13:31
Btw, #1832 was fixing other issues, but in that PR I change the `public/docs/{ts,dart}/latest/guide/glossary.jade` as follows:
```diff
- != partial("../glossary")
+ include ../glossary
```
I don't think that there is any reason to favor the Harp import (via `partial`) vs the Jade `include`. In fact, using Jade allows proper file paths to be used in `makeExample` mixins (rather than the path hacks that used to be there like `makeExample('../docs/_fragments/architecture/ts/app/app.component.ts', ...)`.

**Closed** 2016-08-18 00:50 UTC
Labels: bug
