### ISSUE TITLE
Remove dynamic input type binding from dynamics forms section

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular.io#3052] opened 2016-12-30 15:01 UTC
The [Dynamic Forms demo](https://angular.io/docs/ts/latest/cookbook/dynamic-form.html) demonstrates the ability to bind input [type] and this is misleading because it doesn't work. Thus it should be removed until https://github.com/angular/angular/issues/11716 will be resolved

**Comment by wardbell** [comment] 2017-01-02 22:36
Where is the demo incorrect? I see the followingtextbox in the demo
```
    <input *ngSwitchCase="'textbox'" [formControlName]="question.key"
            [id]="question.key" [type]="question.type">
```
It clearly does work, as we see in this excerpt from Chrome showing the case of an email textbox:
```
<input ng-reflect-name="emailAddress" 
    ng-reflect-id="emailAddress" 
    id="emailAddress" 
    ng-reflect-type="email" 
    type="email" 
    class="ng-untouched ng-pristine ng-valid">
```
Had there been a problem with `input.type` binding it would not have been an illustration of issue #11716 anyway which, it seems, is limited to a binding problem with an attribute binding in the manner of `[attr.xxx]="..."`.  There is such a binding in the cookbook example: `<label [attr.for]="question.key">`.  It works in Chrome (and elsewhere AFAIK):
```
<label for="emailAddress">Email</label>
```

I'm closing this as invalid until you show where precisely the cookbook is incorrect.

**Closed by wardbell** 2017-01-02 22:36 UTC

**Comment by DzmitryShylovich** [comment] 2017-01-02 22:39
u can't dynamically change input type and the illustration of this is
https://github.com/angular/angular/issues/13243
https://github.com/angular/angular/issues/12585
https://github.com/angular/angular/issues/7329
and probably more

**Comment by wardbell** [comment] 2017-01-02 23:01
Huh?

In #13243 didn't change the value of `inputType`. Why would you expect the `<input type>` to change because the type of the `value` changed? In any event, that has nothing to do with this guide.

#12585 and #7329 are irrelevant as they are not use cases in this guide.

This guide does not depend on dynamically changing the input `type`.  It only requires that the `type` be set once.

**Comment by DzmitryShylovich** [comment] 2017-01-02 23:10
Given the component
```
@Component({
  selector: 'my-app',
  template: `<input formControlName="integerB" [type]="inputType"/> `,
})
export class App {
  inputType = "number";
```
u would expect it to initialize `NumberValueAccessor` but in practice it will initialize `DefaulValueAccessor` because inputs are resolved after directives. Not sure if it's a bug or intended behavior but anyway it doesn't work as users expect it to work thus I thnk is should be removed from the docs for now or at least changed to `<input formControlName="integerB" type="number"/> `

**Comment by wardbell** [comment] 2017-01-03 01:07
It can't be `type="number"` because that isn't a binding and the type is determined by the question metadata in this guide example.

You have yet to show that the Dynamic Forms guide behaved other than exactly as expected and described.  I'm not sure where you're seeing these accessors.   If there's a bug, lets fix the bug; the guide is correct.

**Comment by DzmitryShylovich** [comment] 2017-01-03 08:24
> You have yet to show that the Dynamic Forms guide behaved other than exactly as expected and described. 

https://github.com/angular/angular/issues/13243 is not enough?

As u can see http://prntscr.com/dqwwfp the actual type of the input is `number`, but angular still think it's `text`.

> If there's a bug, lets fix the bug

I'm not sure we can call it a bug. It never worked like expected. I would say it's a feature request

**Comment by DzmitryShylovich** [comment] 2017-01-03 11:05
It's simply was not designed to work with inputs. As u can see [here](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/reactive_directives/form_control_directive.ts#L82) CVA is injected on initialization and never changes. This is why it doesn't matter what value u specify for the type, angular will always use `DefaultValueAccessor`.

Exactly the same problem here https://github.com/angular/angular/issues/12585 just different property name.

This is why it should be removed from the docs until it will be implemented.

**Comment by GuyShaanan** [comment] 2017-01-03 20:59
wardbell, if you edit the `question.service.ts` file and add a new TextboxQuestion:

```
new TextboxQuestion({
        key: 'age',
        label: 'Age',
        type: 'number',
        order: 4
      })
```
(notice `type: 'number'`), and try to set any value to the `age` box and hit save, you can *clearly* see that the type of age is **string** and not **number**:

`{"firstName":"Bombasto","brave":"","age":"99"}`

**Comment by wardbell** [comment] 2017-01-03 21:38
@GuyShaanan  I did what you said and it worked just fine in Chrome and Edge
```
      new TextboxQuestion({
        key: 'age',
        label: 'Age',
        value: 21, // <-- also OK with "21"
        type: 'number',
        order: 4
      })
```
Inspecting the HTML in Chrome:
```
<input ng-reflect-name="age" ng-reflect-id="age" id="age" ng-reflect-type="number" 
    type="number" 
    class="ng-pristine ng-valid ng-touched">
```

Why do you think we're getting different results?

**Comment by DzmitryShylovich** [comment] 2017-01-03 21:46
it's a number 21 because it's an initial value. if u change it it should be a string

**Comment by GuyShaanan** [comment] 2017-01-03 21:51
Thanks @wardbell.

Now if you type in any other number and hit save, you'll see that age is now a string, even though the HTML still shows "number".

**Comment by wardbell** [comment] 2017-01-03 21:54
@DzmitryShylovich - confirmed ... and that's not good. Not sure why that is happening (I take it you are sure), and it would be a bug that the dev would have to work around. 

That said, the `<input type>` remains `'number'`  ... as it should be.  I thought your claim was that the `type` binding wouldn't work.

>I'm not sure we can call it a bug. It never worked like expected. I would say it's a feature request

We'll never know if they think its a bug and less we file it as one. 

None of this means the cookbook is wrong ... or should be removed. It does mean that we should warn the reader that s/he must guard the type of the changed value coming from the form and ensure that the proper value goes back into the data object.

I've encountered this problem many times before (sadly) and it always seems to fall on the developer to cope with string values coming out of the UI.

**Comment by DzmitryShylovich** [comment] 2017-01-03 21:57
I will send apr tomorrow but who knows how much time it takes to merge it :)

**Comment by wardbell** [comment] 2017-01-03 21:58
Thank you.  Timing is uncertain. I may be able to whisper something in someone's ear.
