### ISSUE TITLE
Docs show `<boolean>` instead of `Promise<boolean>`

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#1008] opened 2016-03-26 12:16 UTC
docs https://angular.io/docs/ts/latest/api/router/CanDeactivate-interface.html

source https://github.com/angular/angular/blob/2.0.0-beta.12/modules/angular2/src/router/interfaces.ts#L123

**Comment by Foxandxss** [comment] 2016-03-26 18:23
I debugged it. The problem is that we generate our API based on the angular source and you can see:

![](http://puu.sh/nUOhd/172ea86137.png)

Notice the `Promise<boolean>` indentation.

Then that will generate:

![](http://puu.sh/nUOjT/5febb327cc.png)

What my editor marks as blue would be interpreted as `Jade` syntax and the white part will be printed out. Due how Jade works (indentation based) it will interpret the `Promise` as syntax and never print it out.

@wardbell What should we do here? Can be fixed in our side?

**Comment by wardbell** [comment] 2016-03-29 21:44
I believe the best way to address this is by reformatting the signatures in angular/angular.

I create [issue #7819](https://github.com/angular/angular/issues/7819) there and [PR #7820](https://github.com/angular/angular/issues/7820) to fix it.

**Closed by wardbell** 2016-03-29 21:44 UTC
Labels: design love

**Comment by Foxandxss** [comment] 2016-03-29 21:45
Yeah I saw it. It is definitely the less troublesome solution, I like it.
