### ISSUE TITLE
No way found to test the end to end functionality of a Component

### ISSUE THREAD

**Issue by manharthakur** [angular/angular.io#2993] opened 2016-12-16 10:19 UTC
No way found to test the functionality of a Component which uses @angular/core viewContainerRef , elementRef, componentFactoryResolver etc. Document does not specified it completely.
Also raised it before and was closed as code was not provided.

**TEST CASE**

import {TestBed, async,inject,ComponentFixture} from "@angular/core/testing";
import {HighlightDirective} from "../widgets/contact-widget/highlight.directive";
import {ContactState} from "../widgets/contact-widget/contactstate.component";
import { By }              from '@angular/platform-browser';
import { DebugElement }    from '@angular/core';
import { NO_ERRORS_SCHEMA }          from '@angular/core';
describe('Test a Directive', () => {
  let fixture: ComponentFixture<ContactState>;
  beforeEach(() => {
    return TestBed.configureTestingModule({
      declarations: [ContactState],
      
    }).compileComponents().then(() => {
        fixture = TestBed.createComponent(ContactState);
        fixture.detectChanges();
    });
  });
  it('the <p> tag is yellow',() => {
    const de = fixture.debugElement.query(By.css('p'));
    const bgColor = de.nativeElement.style.backgroundColor;
    expect(bgColor).toBe('yellow');
  });
});

**COMPONENT**
import {Component} from '@angular/core';
declare var module: {
    id: string;
};
@Component({
    moduleId: module.id,
    selector: 'contact-state',
    templateUrl: './templates/contactInfo.html'
})
export class ContactState extends CommonStateComponent {
//COMPONENT DATA
 constructor(){}
}

**TEMPLATE**
template content has a p tag which has this directive and the background color is assigned to the p tag contents

**PROBLEM**
nativeElement of undefined
No way to assign value to elementRef so when running a test case it is undefined so further we test case fails.Similar issue with ViewContainerRef and ComponentFactoryResolver when used somewhere in the component.All test cases given in documentation dont specify any such case where these are used and no way given to resolve them in the test case.

**Comment by wardbell** [comment] 2016-12-16 13:04
This doesn't help me. You don't have an `elementRef` anywhere in this example and you aren't saying where the you're getting the `nativeElement of undefined`.

If you want help, please provide a real reproduction, preferably in plunker, and it absolutely must be small and focused. You have far more going on above than is necessary to make your point.

**Comment by manharthakur** [comment] 2016-12-16 14:33
The elementRef is in HighlightDirective whose code is as given 

import { Directive, ElementRef, Input } from '@angular/core';
@Directive(
    { 
        selector: '[myHighlight]' 
    })
export class HighlightDirective 
{
    constructor(el: ElementRef) {
       el.nativeElement.style.backgroundColor = 'yellow';
    }
}

**Comment by manharthakur** [comment] 2016-12-16 16:20
I cant provide you a real reproduction due to some security reasons.

**Comment by wardbell** [comment] 2016-12-16 20:56
Please explain how your case differs from the example of testing the `HighlightDirective` in the Testing Guide.

https://github.com/angular/angular.io/blob/master/public/docs/_examples/testing/ts/app/shared/highlight.directive.spec.ts

That has no trouble getting to the native element.

As you can see from that spec, one creates a test component at attaches the directive-of-interest to it. Then create the test component and probe.

If I was interested in the effect of the directive on a real application component, I'd substitute that for the  test component.

What am I missing?

**Comment by manharthakur** [comment] 2016-12-19 07:05
In your case you are defining you template just at the place where you have spec. In my case we are using a place holder and dynamically replacing the templates. When we just run our test case the template is not loded as application has just compiled but not run so template is not ready yet so it don't get its refrence. Anything related to dynamic templates if you can demonstrate.

**Comment by wardbell** [comment] 2016-12-20 03:54
You realize that in your complaint you did not include the fact that you were dynamically replacing the component (the "component", not the "template", right?).  That's a critical bit of information to have withheld.

To be frank, this is an **advanced use case** that only a relatively small number of people will need.

That's why I find the title you gave this issue &mdash; "_No way found to test the end to end functionality of a Component_" &mdash; particularly irksome. That is simply not true ... as the Testing Guide clearly shows. I will give you the chance to re-title the issue. If you are unable to do so, I will do it for you.

When I have a moment, I'll look into your use case because it interests me. It is not something, however, that we feel deserves high priority and it may not make the guide at all.

**Comment by manharthakur** [comment] 2016-12-22 12:57
We use composite component, where each stage of component is managed by a different template (e.g. something like User registration spanning across 2-3 pages). To take a sample example, a component has three diffrent states(UI stages) i.e in state one it shows a template 1, in state 2 it shows template 2, in state 3 it shows template 3.

Now we use state_mangaement services where we tell it the total no of states and current value of a state for a component during bootstrap and this service register its events.

Code will look like this - 

-----------------------------------------------------------------
import {Component, ComponentFactoryResolver, ViewContainerRef, OnInit, Injector,Attribute} from '@angular/core';
import {state1} from './state1.component';
import {state2} from './state2.component';
import {state3} from './state3.component';
import {SomeClass} from './someclass.component'; //It has the logic of assigning unique values and managing states
@Component({
     template: '<div #placeholder></div>',
    selector: 'common-state',
    entryComponents: [state1,state2,state3]

})
export class CommonState extends SomeClass implements OnInit{
    constructor(
        @Attribute('id') id: string,
        @Attribute('Keys') Keys: string,
        elementRef?: ViewContainerRef       
    ) {
    
    super(
            id,
            Keys,
            elementRef     
         );
    }
    
    ngOnInit(){
        super.pushComponent("State1",state1);
        super.pushComponent("State1",state1);
        super.pushComponent("State1",state1);
        super.ngOnInit("State1");
    }
}

-----------------------------------------------------------------

The supers ngOnInit has the following code

    ngOnInit(defaultState:string) {
        this.uniqueId = this.generateUniqueId();      
        this.elementRef.element.nativeElement["id"] = this.uniqueId;
        this.changeState({state:defaultState});
    }
-----------------------------------------------------------------

The state1 component has the following type of code and all three states have similar kind of code

import {Component} from '@angular/core';
@Component({
    moduleId:module.id,
    selector: 'state-1',
    templateUrl: './templates/state1.html',
})

export class State1 { 
    subsharedstate:any={};
    constructor() {
        
    }
//some functions
}
-----------------------------------------------------------------
We use the common state selector in a template of one commonStateMainComponent

import {Component} from '@angular/core';
    
@Component({
    moduleId: module.id,
    selector: 'service-setup-component',
    templateUrl: './templates/commonStateMainComponent.html',
})

export class commonStateMainComponent{
}
-----------------------------------------------------------------
CommonStateMainComponent has following template

<common-state></common-state>
-----------------------------------------------------------------

Now we are using elementRef to check stuff from a specific state but elementRef get its value at run time(when angularjs replace #placeholder with actual state template) and our test spec fails as we are not actually running the application.

So we need some sort of way to get the replaced/updated elementRef value during our test case execution.

**Comment by manharthakur** [comment] 2017-01-02 11:51
A gentle reminder for the same problem, if there is a solution regarding the same or anything more is required by you.

**Comment by wardbell** [comment] 2017-01-02 21:42
I have no trouble at all getting an instance of the `viewContainerRef` from within a test.

For example, in the testing sample inside `bag.ts` I modified the `ParentComponent` to inject its `ViewContainerRef` and make it a public property
```
@Component({
  selector: 'parent-comp',
  template: `Parent(<child-1></child-1>)`
})
export class ParentComponent {
  constructor(public viewContainerRef: ViewContainerRef) {
    const el = viewContainerRef.element.nativeElement as HTMLElement;
  }
}
```
I modified `bag.spec.ts` to inspect it.
```
  beforeEach( async(() => {
    TestBed.configureTestingModule({
      declarations: [ParentComponent, FakeChildComponent]
    })
    .compileComponents();
  }));
 ...
  it('ParentComp should have viewContainerRef', () => {
    const fixture = TestBed.createComponent(ParentComponent);
    fixture.detectChanges();
    expect(fixture.componentInstance.viewContainerRef).toBeTruthy();
  });
```
The test passes.

You're doing something wrong. It's not Angular's fault or a lack of documentation that stands between you and success. I suggest you simplify and work up from working tests until you discover your error.

This is a place for diagnosed issues. It is not the right forum for implementation questions. StackOverflow might be better. 

It's also not a mainstream testing scenario that I feel merits documentation at this time. So I'm closing this comment.

**Closed by wardbell** 2017-01-02 21:42 UTC
