### ISSUE TITLE
5-minute Quickstart Typescript Error Fix

### ISSUE THREAD

**Issue by AbdullahAlger** [angular/angular.io#99] opened 2015-05-08 09:07 UTC
If you are following the quickstart guide, you might notice that after installing Typescript you get the following error after running the command ```tsc --watch -m commonjs -t es5 --emitDecoratorMetadata app.ts```:

```
error TS5023: Unknown compiler option 'emitdecoratormetadata'.
```

In order to solve the problem, I ran ``` npm install -g typescript  ```. Maybe the tutorial should be updated if others are having the same issue.

**Comment by rkirov** [comment] 2015-05-08 17:29
The quick starts says:
```
$ npm install -g typescript@^1.5.0-beta
$ tsc --watch -m commonjs -t es5 --emitDecoratorMetadata app.ts
```
That should guarantee you have the minimum supported TS version, right before you run `tsc`.

**Comment by AbdullahAlger** [comment] 2015-05-08 17:32
Believe it or not, that's what I did before I got the error.

**Comment by alexeagle** [comment] 2015-05-08 20:13
hrm, I cannot reproduce
```
alexeagle-macbookpro2:~ alexeagle$ npm uninstall -g typescript
unbuild typescript@1.5.0-beta
alexeagle-macbookpro2:~ alexeagle$ npm install -g typescript@1.4.1
/Users/alexeagle/.nvm/versions/node/v0.12.2/bin/tsc -> /Users/alexeagle/.nvm/versions/node/v0.12.2/lib/node_modules/typescript/bin/tsc
typescript@1.4.1 /Users/alexeagle/.nvm/versions/node/v0.12.2/lib/node_modules/typescript
alexeagle-macbookpro2:~ alexeagle$ npm install -g typescript@^1.5.0-beta
/Users/alexeagle/.nvm/versions/node/v0.12.2/bin/tsc -> /Users/alexeagle/.nvm/versions/node/v0.12.2/lib/node_modules/typescript/bin/tsc
/Users/alexeagle/.nvm/versions/node/v0.12.2/bin/tsserver -> /Users/alexeagle/.nvm/versions/node/v0.12.2/lib/node_modules/typescript/bin/tsserver
typescript@1.5.0-beta /Users/alexeagle/.nvm/versions/node/v0.12.2/lib/node_modules/typescript
alexeagle-macbookpro2:~ alexeagle$ tsc --version
message TS6029: Version 1.5.0-beta
```

**Comment by alexeagle** [comment] 2015-05-08 20:15
@AbdullahAlger can you run `npm -v; node -v`

**Comment by AbdullahAlger** [comment] 2015-05-08 20:26
I have npm 2.5.1 and node 0.12.0.

**Comment by alexwolfe** [comment] 2015-05-17 18:01
@rkirov I'll let you fix or close this issue. Assigned to you now.

**Comment by WonSong** [comment] 2015-05-20 03:56
@AbdullahAlger 

I had a similar problem on Windows 8.1 with Visual Studio installed. 

If you are as well, try ```where tsc``` command. 
It will show you list of TypeScript compilers installed in your system. 

I was able to by pass this error by using 
```tsc.cmd --watch -m commonjs -t es5 --emitDecoratorMetadata app.ts``` instead of just ```tsc```

**Comment by AbdullahAlger** [comment] 2015-05-20 08:22
@WonSong 

I use a Mac; however, thanks for the tip. As my original post said, I got it working by just installing 

```npm install -g typescript```

I was just pointing out that I had trouble with the installation at ```npm install -g typescript@^1.5.0-beta``` and went around the issue myself. I am not entirely sure why the Angular tutorial would prefer ```npm install -g typescript@^1.5.0-beta``` over ```npm install -g typescript```.  

I will try again to see if the issue comes up. I've updated my npm from 2.5.1 to 2.10.0. Might be the issue, but probably not.

**Comment by Twistt** [comment] 2015-07-08 00:18
I had a similar problem where it was using the "wrong" tsc with the following error: error TS5023: Unknown option 'watch'
Fixed by changing tsc to tsc.cmd

**Comment by tjosbon** [comment] 2015-07-08 13:15
@Twistt changing it from "tsc" to "tsc.cmd" worked for me as well, thanks for posting!

**Comment by tjosbon** [comment] 2015-07-08 13:16
fyi ... didn't see a pull request to update the documentation.  Please correct me if I overlooked it.  Otherwise, I'll create a quick pull request to update.

**Comment by AbdullahAlger** [comment] 2015-07-08 13:56
It's a Windows thing. Regarding `tsc.cmd`, apparently it's a TypeScript installation problem. See [SO question](http://stackoverflow.com/questions/23267858/how-do-i-install-typescript).

**Comment by tjosbon** [comment] 2015-07-08 14:04
@AbdullahAlger worth noting in the documentation?  I had to search for this issue to discover the problem.  I can pick up that task.

**Comment by AbdullahAlger** [comment] 2015-07-08 14:10
@tjosbon 
Why not!? The only thing that could happen is that it's rejected.

**Comment by brendonco** [comment] 2015-07-10 05:59
Hi, I'm still getting tsc error when I follow to install the tsc and run 

tsc --watch -m commonjs -t es5 --emitDecoratorMetadata app.ts

error TS5023: Unknown option 'watch'

**Comment by minwe** [comment] 2015-07-15 06:34
I got the error, too.

```
angular2/src/di/decorators.d.ts(34,13): error TS1003: Identifier expected.
angular2/src/di/decorators.d.ts(37,17): error TS1003: Identifier expected.
angular2/src/di/decorators.d.ts(45,13): error TS1003: Identifier expected.
angular2/src/di/decorators.d.ts(48,17): error TS1003: Identifier expected.
angular2/src/di/decorators.d.ts(56,13): error TS1003: Identifier expected.
angular2/src/di/decorators.d.ts(59,17): error TS1003: Identifier expected.
```

Env:

```
OS: Macintosh; Intel Mac OS X 10_10_4
node -v v0.12.7
npm -v 3.1.2
tsc -v message TS6029: Version 1.5.0-beta
angular2@2.0.0-alpha.31
```

**Comment by vbilici** [comment] 2015-07-16 13:20
same situation with @minwe with the same environment.

**Comment by AbdullahAlger** [comment] 2015-07-16 13:33
Have you tried installing TypeScript as 
    npm install -g typescript
Instead of version 1.5 beta? I did that and it worked for me.

**Comment by vbilici** [comment] 2015-07-16 13:51
yep,
it gives this error message:
command: tsc --watch -m commonjs -t es5 --emitDecoratorMetadata app.ts
error TS5023: Unknown compiler option 'emitdecoratormetadata'.

**Comment by benjaminmbrown** [comment] 2015-07-20 18:21
Using tsc.cmd worked for me as I was experiencing the same thing.

**Comment by brendonco** [comment] 2015-07-21 13:51
I was able to make it work and created a working template and steps how to install and run the TypeScript compiler.

https://github.com/brendonco/angular2-template

**Closed** 2015-07-21 17:10 UTC

**Comment by matsko** [comment] 2016-02-13 03:25
Installing `npm install typescript -g` worked for me.

**Comment by himanshupareek** [comment] 2016-04-28 16:32
@Twistt changing it from "tsc" to "tsc.cmd" worked for me as well, thanks for posting!

**Comment by boldwade** [comment] 2016-07-10 04:53
Yep, if you change your environment variables to use the 1.8 version of tsc instead of the 1.0 version of tsc, you won't have to use tsc.cmd, but just the tsc command.

**Comment by azjkjensen** [comment] 2016-07-13 20:21
@boldwade which environment variables?

**Comment by boldwade** [comment] 2016-07-27 19:19
@azjkjensen, your path. Add the 1.8 tsc folder location to your path (environment variables for your system). I had a similar problem as the people above. At some point I added the typescript plugin or whatever for visual studio and it then set my environment variables to use their version of the tsc first, before the NPM one. So, if you just reverse that, you should be GTG.

**Comment by gtproys** [comment] 2017-11-28 22:42
ajalger solution works for me, i was using an older version of typescript

Thanks
