### ISSUE TITLE
Menu Navigation 404 not found error

### ISSUE THREAD

**Issue by kuntal-b** [angular/angular.io#928] opened 2016-03-08 08:48 UTC
Issue described bellow link

https://github.com/angular/angular/issues/7486

**Comment by zoechi** [comment] 2016-03-08 11:04
dup of #927

**Comment by skeep** [comment] 2016-03-08 11:11
problem is the link to going to `https://angular.io/docs/ts/latest/api.html` where as it's expected to go to `https://angular.io/docs/ts/latest/api/` or `https://angular.io/docs/ts/latest/api/index.html`

**Comment by bjwyse** [comment] 2016-03-08 15:19
Duplicate of https://github.com/angular/angular.io/issues/927. Please close.

**Comment by wardbell** [comment] 2016-03-08 17:42
closed as dup

**Closed by wardbell** 2016-03-08 17:42 UTC
