### ISSUE TITLE
[http testing] Outdated MockBackend documentation, missing http testing examples

### ISSUE THREAD

**Issue by alexbyk** [angular/angular.io#2505] opened 2016-09-29 13:42 UTC
I tried to write a test with mocking 'http' service and faced a problem: all internet "howtos" are outdated, there is no official example in the "Advanced/Testing", and the API reference for the MockBackend is outdated(or contains bugs?).

I would be great to have an official example how to deal with http in tests

**Comment by Foxandxss** [comment] 2016-09-30 21:44
Duplicate of #2499

**Closed by Foxandxss** 2016-09-30 21:45 UTC
