### ISSUE TITLE
The Hero Editor example in plunker has errors and does not run.

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#568] opened 2015-12-16 22:03 UTC
URL: https://angular.io/docs/ts/latest/tutorial/

I tried and see it stuck on Loading... in plunkr, with chrome 47.

**Comment by johnpapa** [comment] 2015-12-16 22:39
yes, this is due to a new issue beta 0 introduced. this line of code causes it

`<div *ngFor="#hero of heroes | slice:0:4" class="col-1-4" (click)="gotoDetail(hero)">`

I can remove it for now til the issue is resolved.

here is the issue https://github.com/angular/angular/issues/5918

**Comment by johnpapa** [comment] 2015-12-17 02:30
fixed now as per the merge tonight

the slice pipe is removed and is not being handled in code.

**Comment by johnpapa** [comment] 2015-12-17 02:31
please verify and close @naomiblack

**Comment by wardbell** [comment] 2015-12-18 18:45
Fixed at least as of f4acc0ccbcb167d769edce892f1d3bfde0810707

**Closed by wardbell** 2015-12-18 18:45 UTC
