### ISSUE TITLE
The click event handler raises an exception (even with empty body, ES5)

### ISSUE THREAD

**Issue by Dotneteer** [angular/angular.io#475] opened 2015-12-11 07:16 UTC
Using `angular2-polyfill.js` and `angular2.umd.js` raises an exception right after running the click event handler (`TypeError: l_context.onClickMe is not a function`). The event handler body runs (it can be even empty), the exception is raised:

You can find the plunker here: http://plnkr.co/edit/OjnOz7h7L2W7fPSD9pSx?p=preview

Click "Click me", and see the console log.

```JavaScript
(function() {

var ClickMeComponent = ng.core
.Component({
  selector: 'click-me',
  template: '<button (click)="onClickMe()">Click me</button>'
})
.Class({
  constructor: function() {
    this.onClickMe = function() {
      // console.log("You are my hero!")
    }
  }
});

var AppComponent = ng.core
.Component({
  selector: 'my-app',
  templateUrl: 'app/app.html',
  directives: [
    ClickMeComponent,
  ]
})
.Class({
  constructor: function() { }
});

document.addEventListener('DOMContentLoaded', function() {
  ng.platform.browser.bootstrap(AppComponent);
});

})()
```

**Comment by pkozlowski-opensource** [comment] 2015-12-11 08:53
Duplicate of https://github.com/angular/angular/issues/5823 - please don't open multiple entries for the same problem...

**Closed** 2015-12-11 08:56 UTC
