### ISSUE TITLE
Broken hyperlink in dart doc for ControlValueAccessor class

### ISSUE THREAD

**Issue by ben4ever** [angular/angular.io#2126] opened 2016-08-17 00:22 UTC
If you search for the hyperlink named "ControlValueAccessor" on https://angular.io/docs/dart/latest/guide/template-syntax.html and click on it, it leads to a 404.

**Comment by chalin** [comment] 2016-08-22 20:28
Thanks for reporting this. The issue is broader in scope and will be fixed as part of #2173, so we'll close this issue and track progress in #2173.

**Closed** 2016-08-22 20:56 UTC
Labels: dart
