### ISSUE TITLE
Plunker Typescript demo not working due to Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by pauldevilliers** [angular/angular.io#2230] opened 2016-08-31 14:38 UTC
I'm submitting a ... (check one with "x")

[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
Current behavior

The Plunker Typescript demo was working until this morning - when I noticed that it stopped with the following error in the browser:

XMLHttpRequest cannot load https://npmcdn.com/plugin-typescript@4.0.10/lib/plugin.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.

I then noticed that my Node system on windows was generating the same error - so this is basically stopping the demo/online code from running as well as the offline development environment...

Please tell us about your environment:

Angular version: 2.0.0-rc.1

Browser: [all]

Language: [TypeScript 1.9.0 ]

**Comment by pauldevilliers** [comment] 2016-08-31 14:39
Sorry, the link for the demo is

https://angular.io/resources/live-examples/quickstart/ts/plnkr.html

**Comment by Foxandxss** [comment] 2016-09-02 14:24
Should be fixed by now.

**Closed by Foxandxss** 2016-09-02 14:24 UTC

**Comment by hmlnarik** [comment] 2016-09-08 07:07
Seems that the issue has started appearing today again. Yesterday plunker [1] was working fine, now it is rejected with _XMLHttpRequest cannot load https://npmcdn.com/plugin-typescript@4.0.10/lib/plugin.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access._ message in browser console.

**Comment by yaroslavya** [comment] 2016-09-08 09:17
As a temporary workaround you can use some app/browser extension to modify the headers on the fly.
I used [requestly](http://requestly.in/) and added a response rule that will add the `Access-Control-Allow-Origin: *` header to any response that is from `npmcdn.com`. That fixed all the angular2 plunkers for me.

**Comment by hmlnarik** [comment] 2016-09-08 09:28
@yaroslavya Thanks for the workaround. Yes, that works for me though fixing the cause would be a better option visible for other people as well.

**Comment by Foxandxss** [comment] 2016-09-08 09:35
Weird, what plunker you say if fails? We are not even using npmcdn.com url anymore.

**Comment by yaroslavya** [comment] 2016-09-08 09:40
@Foxandxss any that is using it. I had troubles with this one http://plnkr.co/edit/SL949g1hQQrnRUr1XXqt?p=preview
Seems some of the plunkers just used npmcdn and it changed the CORS header. But seems like this is a wrong place for this issue. Should we move it anywhere? As it may be a good reference point to anyone, until its fixed.

**Comment by hmlnarik** [comment] 2016-09-08 09:40
Ah that can be the issue then - I used a plunker sample referred from stackoverflow (added the Plunker URL to the original question). What URL should be used instead of npmcdn.com?

**Comment by Foxandxss** [comment] 2016-09-08 09:49
Let me do some questions and I will come back later to this.

**Comment by Foxandxss** [comment] 2016-09-08 10:43
The problem is with npmcdn that has that bug, if you change it to unpkg.com (which is the new URL) it works.

**Comment by hmlnarik** [comment] 2016-09-08 11:21
Thank you, unpkg.com works for me. Now that I look at it, https://npmcdn.com/ redirects via HTTP 302 to https://unpkg.com/ and does not contain Access-Control-Allow-Origin:* header in the 302 response. That might be the root cause of the issue - answers from [1] seem to be highly relevant.

[1] http://stackoverflow.com/questions/18539403/chrome-cancels-cors-xhr-upon-http-302-redirect
