### ISSUE TITLE
New Router - Clear up the intended behavior and significance in the order routes are defined.

### ISSUE THREAD

**Issue by jspenc72** [angular/angular.io#2506] opened 2016-09-29 15:36 UTC
Please see the following issue as a reference.

https://github.com/angular/angular/issues/10474

**Comment by brandonroberts** [comment] 2016-10-01 00:24
An explanation of the route order is already stayed in the router guide.

`
The order of the routes in the configuration matters and this is by design. The router uses a first-match wins strategy when matching routes, so more specific routes should be placed above less specific routes. In our configuration above, the routes with a static path are listed first, followed by an empty path route, that matches as the default route. The wildcard route is listed last as it's the most generic route and should be matched only if no other routes are matched first.
`

**Comment by wardbell** [comment] 2016-10-03 23:30
Closing for reasons stated by Brandon

**Closed by wardbell** 2016-10-03 23:30 UTC
Labels: wontfix
